add_subdirectory(minelf)
add_subdirectory(minui)
add_subdirectory(libpixelflinger)
add_subdirectory(minzip)
add_subdirectory(libcutils)
add_subdirectory(mtdutils)
add_subdirectory(liblog)
add_subdirectory(libmincrypt)
add_subdirectory(ext4utils)
add_subdirectory(libsparse)
add_subdirectory(bionic)
add_subdirectory(libpng)
